services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    secrets:
      - private-key
      - public-crt
    volumes:
      - ./html:/usr/share/nginx/html
secrets:
  private-key:
    file: ./nginx/nginx.key
  public-crt:
    file: ./nginx/nginx.crt
